name: Python Example with pytest
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Run pytest-benchmark benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Run benchmark
        run: |
          cd examples/pytest
          pip install -r requirements.txt
          pytest bench.py --benchmark-json output.json
      - name: Store benchmark result
        if: ${{ github.event_name == 'push' }}
        uses: AzHicham/github-action-benchmark@v2
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: examples/pytest/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@AzHicham'
          commit-id: ${{ github.event.head_commit.id }}
          commit-message: ${{ github.event.head_commit.message }}
          commit-timestamp: ${{ github.event.head_commit.timestamp }}
          commit-url: ${{ github.event.repository.html_url }}
          commit-name: ${{ github.event.head_commit.author.name }}/commits/${{ github.event.head_commit.id }}
      - name: Store benchmark result
        if: ${{ github.event_name == 'pull_request' }}
        uses: AzHicham/github-action-benchmark@v2
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: examples/pytest/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@AzHicham'
          commit-id: ${{ github.event.pull_request.head.sha }}
          commit-message: ${{ github.event.pull_request.title }}
          commit-timestamp: ${{ github.event.pull_request.head.repo.updated_at }}
          commit-url: ${{ github.event.pull_request.html_url }}/commits/${{ github.event.pull_request.head.sha }}
          commit-name: ${{ github.event.pull_request.head.user.login }}
